# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'binarium'
description: 'Zero-configuration library and CLI for building node executables for all platforms and architectures'
author: 'pigeonposse'
inputs:
  build:
    required: false
    default: 'node'
    description: 'Specify the runtime environment. Acceptable values are: node, deno, bun.'
  config:
    required: false
    description: 'Path for config file.'
    default: './binarium.config.json'

runs:
  using: "composite"
  steps:
    - name: ⬇️🥡 Install pnpm
      uses: pnpm/action-setup@v4
    - name: ⬇️🟢 Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: ⚠️ Validate build input
      run: |
        if [[ "${{ inputs.build }}" != "node" && "${{ inputs.build }}" != "deno" && "${{ inputs.build }}" != "bun" ]]; then
          echo "Error: Invalid input for 'build'. Acceptable values are: node, deno, bun."
          exit 1
        fi
      shell: bash
    - name: ⬇️📦 Install dependencies
      run: pnpm i -g binarium
      shell: bash

    - name: 🧩📦 Execute bepp
      run: binarium ${inputs.build} --config '${{ inputs.config }}'
      shell: bash

branding:
  icon: 'package'
  color: 'purple'
