onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  axios@>=1.0.0 <1.8.2: '>=1.8.2'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  tar-fs@>=2.0.0 <2.1.2: '>=2.1.2'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tar@<=7.5.2: '>=7.5.3'
  tmp@<=0.2.3: '>=0.2.4'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
